name: CI

on: [push, pull_request]


env:
  HPCX_PKG_NAME: hpcx-v2.8.1-gcc-MLNX_OFED_LINUX-5.2-2.2.0.0-ubuntu20.04-x86_64
  HPCX_PKG_LINK: http://www.mellanox.com/downloads/hpc/hpc-x/v2.8.1
  OPEN_UCX_LINK: https://github.com/openucx/ucx
  MOFED_PKG_NAME: MLNX_OFED_LINUX-5.2-2.2.0.0-ubuntu20.04-x86_64
  MOFED_PKG_LINK: http://www.mellanox.com/downloads/ofed/MLNX_OFED-5.2-2.2.0.0
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get MOFED
      run: wget "${MOFED_PKG_LINK}/${MOFED_PKG_NAME}.tgz" -P /tmp
    - name: Unpack MOFED
      run: cd /tmp && tar -xf "${MOFED_PKG_NAME}.tgz"
    - name: Install MOFED
      run: |
        cd /tmp/${MOFED_PKG_NAME}
        sudo ./mlnxofedinstall --basic --user-space-only --without-fw-update --all  -q --force --without-neohost-backend
    - name: Get HPCX
      run: wget "${HPCX_PKG_LINK}/${HPCX_PKG_NAME}.tbz" -P /tmp
    - name: Unpack HPCX
      run: cd /tmp && tar xjf "${HPCX_PKG_NAME}.tbz"
    - name: Get UCX
      run: git clone ${OPEN_UCX_LINK} /tmp/ucx
    - name: Build UCX
      run: cd /tmp/ucx && ./autogen.sh && ./contrib/configure-release-mt --without-java --disable-numa --prefix $PWD/install && make -j install
    - uses: actions/checkout@v1
    - name: Build
      run: |
        source /tmp/${HPCX_PKG_NAME}/hpcx-init.sh; hpcx_load
        ./autogen.sh
        ./configure --prefix=$PWD/install --with-ucx=/tmp/ucx/install
        make -j`nproc` install
    - name: Build XCCL tests
      run: |
        source /tmp/${HPCX_PKG_NAME}/hpcx-init.sh; hpcx_load
        export LD_LIBRARY_PATH=/tmp/ucx/install/lib:$LD_LIBRARY_PATH
        export LIBRARY_PATH=/tmp/ucx/install/lib:$LIBRARY_PATH
        export CPATH=/tmp/ucx/install/lib:$CPATH
        make -C test
    - name: Test run
      run: |
        source /tmp/${HPCX_PKG_NAME}/hpcx-mt-init.sh; hpcx_load
        export LD_LIBRARY_PATH=/tmp/ucx/install/lib:$LD_LIBRARY_PATH
        export UCX_SOCKADDR_TLS_PRIORITY=tcp
        mpirun --oversubscribe -x XCCL_TEST_TLS=hier -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_allreduce
        mpirun --oversubscribe -x XCCL_TEST_TLS=hier -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_bcast
        mpirun --oversubscribe -x XCCL_TEST_TLS=hier -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_barrier

        mpirun --oversubscribe -x XCCL_TEAM_HIER_NODE_LEADER_RANK_ID=3 -x XCCL_TEST_TLS=hier -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_allreduce
        mpirun --oversubscribe -x XCCL_TEAM_HIER_NODE_LEADER_RANK_ID=4 -x XCCL_TEST_TLS=hier -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_bcast
        mpirun --oversubscribe -x XCCL_TEAM_HIER_NODE_LEADER_RANK_ID=5 -x XCCL_TEST_TLS=hier -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_barrier

        mpirun --oversubscribe -x XCCL_TEAM_UCX_ALLREDUCE_ALG_ID=0 -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_allreduce
        mpirun --oversubscribe -x XCCL_TEAM_UCX_ALLREDUCE_ALG_ID=1 -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_allreduce
        mpirun --oversubscribe -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_bcast
        mpirun --oversubscribe -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_barrier
        mpirun --oversubscribe -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_alltoall
        mpirun --oversubscribe -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_alltoallv
        mpirun --oversubscribe -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_allgather
        mpirun -x XCCL_TEAM_UCX_ALLTOALL_PAIRWISE_CHUNK=0 --oversubscribe -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_alltoall
        mpirun -x XCCL_TEAM_UCX_ALLTOALL_PAIRWISE_CHUNK=0 --oversubscribe -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_alltoallv
        mpirun --oversubscribe -x XCCL_TEST_TLS=hier -x XCCL_TEST_ITERS=500  -x XCCL_TEST_NTHREADS=4 -x XCCL_TEST_CHECK=1 -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_mt
